services:
  jwt:
    build:
      context: ./JWTService
      dockerfile: Dockerfile
    env_file:
      - ./JWTService/.env
    ports:
      - "8001:8001"
    networks:
      - main

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - main

  auth:
    build:
      context: ./AuthorizationService
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - main
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator
    ports:
      - "5432:5432"
    networks:
      - main





networks:
  main:
    driver: bridge