openapi: 3.0.0
info:
  title: Organizer Registration API
  version: 1.0.0
  description: API для регистрации организаторов.

paths:
  /register_organizer:
    post:
      summary: Регистрация организатора
      description: Принимает данные организатора и регистрирует его.
      operationId: registerOrganizer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Электронная почта организатора.
                company:
                  type: string
                  description: Название компании организатора.
                TIN:
                  type: string
                  description: Идентификационный номер налогоплательщика (ИНН).
              required:
                - email
                - company
                - TIN
      responses:
        '200':
          description: Успешная регистрация организатора.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
        '400':
          description: Неверный запрос (например, недействительный email).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "bad request"
        '500':
          description: Внутренняя ошибка сервера.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "internal server error"