openapi: 3.0.0
info:
  title: AuthorizationService API
  version: 1.0.0
  description: API для регистрации, авторизации

servers:
  - url: http://localhost:8002
    description: Локальный сервер разработки

paths:
  /organizer/register:
    post:
      summary: Регистрация организатора
      description: Принимает данные организатора и регистрирует его.
      operationId: registerOrganizer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
<<<<<<< HEAD
                    type: string
                    format: email
                    description: Электронная почта организатора
                    example: "organizer_email@gmail.com"
                company:
                    type: string
                    description: Название компании организатора
                    example: "ООО 'Рога и копыта'"
                TIN:
                    type: string
                    description: Идентификационный номер налогоплательщика (ИНН)
                    example: "123456789012"
=======
                  type: string
                  format: email
                  description: Электронная почта организатора
                    type: string
                    format: email
                    description: Электронная почта организатора
                    example: "organizer_email@gmail.com"
                company:
                    type: string
                    description: Название компании организатора
                    example: "ООО 'Рога и копыта'"
                TIN:
                  type: string
                  description: Идентификационный номер налогоплательщика (ИНН)
>>>>>>> 23a005e (documentation added)
                    type: string
                    description: Идентификационный номер налогоплательщика (ИНН)
                    example: "123456789012"
              required:
                - email
                - company
                - TIN
      responses:
        '200':
          description: Успешная регистрация организатора
        '400':
          description: Неверный запрос (например, недействительный email или занятый email)
        '500':
          description: Внутренняя ошибка сервера

  /user/register:
    post:
      summary: Регистрация пользователя
      description: Регистрация нового пользователя в системе
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
<<<<<<< HEAD
                    type: string
                    description: Имя пользователя
                    example: "Иван"
                last_name:
                    type: string
                    description: Фамилия пользователя
                    example: "Иванов"
                email:
                    type: string
                    format: email
                    description: Электронная почта пользователя
                    example: "ivan_ivanov@gmail.com"
                login:
                    type: string
                    description: Логин пользователя
                    example: "ivan_ivanov"
                password:
                    type: string
                    description: Пароль пользователя
                    example: "1234567890"
                user_id:
                    type: string
                    description: ID пользователя из сервиса пользователя
                    example: "1234567890"
=======
                  type: string
                  description: Имя пользователя
                    type: string
                    description: Имя пользователя
                    example: "Иван"
                last_name:
                    type: string
                    description: Фамилия пользователя
                    example: "Иванов"
                email:
                    type: string
                    format: email
                    description: Электронная почта пользователя
                    example: "ivan_ivanov@gmail.com"
                login:
                    type: string
                    description: Логин пользователя
                    example: "ivan_ivanov"
                password:
                    type: string
                    description: Пароль пользователя
>>>>>>> 23a005e (documentation added)
                    example: "1234567890"
                user_id:
                    type: string
                    description: ID пользователя из сервиса пользователя
                    example: "1234567890"
              required:
                - name
                - last_name
                - email
                - login
                - password
<<<<<<< HEAD
                - user_id
=======
>>>>>>> 23a005e (documentation added)
                - user_id
      responses:
        '200':
          description: Успешная регистрация пользователя
        '400':
          description: Неверный запрос (например, недействительный email или занятый email)
        '500':
          description: Внутренняя ошибка сервера

  /authorize:
    post:
      summary: Авторизация пользователя
      description: Аутентификация пользователя и получение JWT токена
      operationId: authorizeUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
<<<<<<< HEAD
                    type: string
                    format: login
                    description: Логин пользователя
                password:
                    type: string
                    format: password
                    description: Пароль пользователя
=======
                  type: string
                  format: login
                  description: Логин пользователя
                    type: string
                    format: login
                    description: Логин пользователя
                password:
                  type: string
                  format: password
                  description: Пароль пользователя
>>>>>>> 23a005e (documentation added)
                    type: string
                    format: password
                    description: Пароль пользователя
              required:
                - login
                - password
      responses:
        '200':
          description: Успешная авторизация
        '401':
          description: Неверные учетные данные
        '500':
          description: Внутренняя ошибка сервера

  /admin/create:
    post:
      summary: Создание администратора
      description: Создание нового администратора в системе
      operationId: createAdmin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
<<<<<<< HEAD
                    type: string
                    description: Имя администратора
                    example: "VERY_SECRET_KEY"
                login:
                    type: string
                    description: Фамилия администратора
                    example: "admin"
                password:
                    type: string
                    description: Электронная почта администратора
                    example: "admin228"
                email:
                    type: string
                    description: Логин администратора
                    example: "admin_email@gmail.com"
=======
                  type: string
                  description: Имя администратора
                    type: string
                    description: Имя администратора
                    example: "VERY_SECRET_KEY"
                login:
                    type: string
                    description: Фамилия администратора
                    example: "admin"
                password:
                    type: string
                    description: Электронная почта администратора
                    example: "admin228"
                email:
                  type: string
                  description: Логин администратора
>>>>>>> 23a005e (documentation added)
                    type: string
                    description: Логин администратора
                    example: "admin_email@gmail.com"
              required:
               - api_key
               - login
               - password
               - email
      responses:
        '200':
          description: Успешное создание администратора
        '400':
          description: Неверный запрос (например, недействительный email или занятый email)
        '403':
          description: Неверный ключ апи
        '409':
          description: Администратор с таким логином уже существует

  /admin/authorize:
    post:
      summary: Авторизация администратора
      description: Аутентификация администратора и получение JWT токена
      operationId: authorizeAdmin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
<<<<<<< HEAD
                    type: string
                    description: Ключ апи
                    example: "VERY_SECRET_KEY"
                email:
                    type: string
                    format: email
                    description: Электронная почта администратора
                    example: "admin_email@gmail.com"
                login:
                    type: string
                    format: login
                    description: Логин администратора
                    example: "admin"
                password:
                    type: string
                    format: password
                    description: Пароль администратора
                    example: "admin228"
=======
                  type: string
                  description: Ключ апи
                    type: string
                    description: Ключ апи
                    example: "VERY_SECRET_KEY"
                email:
                    type: string
                    format: email
                    description: Электронная почта администратора
                    example: "admin_email@gmail.com"
                login:
                    type: string
                    format: login
                    description: Логин администратора
                    example: "admin"
                password:
                  type: string
                  format: password
                  description: Пароль администратора
>>>>>>> 23a005e (documentation added)
                    type: string
                    format: password
                    description: Пароль администратора
                    example: "admin228"
              required:
                - api_key
                - email
                - login
                - password
      responses:
        '200':
          description: Успешная авторизация
        '403':
          description: Неверный ключ апи или пароль
        '500':
          description: Внутренняя ошибка сервера

  /organizer/approve:
    post:
      summary: Подтверждение регистрации
      description: Подтверждение регистрации пользователя или организатора
      operationId: approveRegistration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
<<<<<<< HEAD
                    type: string
                    format: email
                    description: Электронная почта организатора
                    example: "organizer_email@gmail.com"
                company:
                    type: string
                    description: Название организации
                    example: "ООО 'Рога и копыта'"
                tin:
                    type: string
                    description: ИНН организации
                    example: "123456789012"
                status:
                    type: string
                    description: Статус подтверждения
                    example: "APPROVED"
                user_id:
                    type: string
                    description: ID организатора из сервиса пользователя
                    example: "1234567890"
              required:
                - email
                - company
                - tin
                - status
                - user_id
=======
                  type: string
                  format: email
                  description: Электронная почта организатора
                organization_name:
                  type: string
                  description: Название организации
                    type: string
                    format: email
                    description: Электронная почта организатора
                    example: "organizer_email@gmail.com"
                company:
                    type: string
                    description: Название организации
                    example: "ООО 'Рога и копыта'"
                tin:
                    type: string
                    description: ИНН организации
                    example: "123456789012"
                status:
                    type: string
                    description: Статус подтверждения
                    example: "APPROVED"
                user_id:
                    type: string
                    description: ID организатора из сервиса пользователя
                    example: "1234567890"
              required:
                - email
                - company
                - tin
                - status
>>>>>>> 23a005e (documentation added)
                - user_id
      responses:
        '200':
          description: Успешное подтверждение регистрации
        '403':
          description: Отказано в доступе

  /password/change:
    put:
      summary: Изменение пароля
      description: Изменение пароля пользователя или организатора
      operationId: changePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: Логин пользователя или организатора
                password:
                  type: string
                  description: Новый пароль
              required:
                - login
                - password
      responses:
        '200':
          description: Пароль успешно изменен
        '400':
          description: Неверный запрос или пользователь не найден
