openapi: 3.0.0
info:
  title: PaymentsService API
  version: 1.0.0
  description: API для работы с платежами

servers:
  - url: http://localhost:8008
    description: Локальный сервис разработки

paths:
  /payments/create:
    post:
      summary: Создание платежа
      description: Создание платежа и получение ссылки на оплату
      operationId: createPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: Идентификатор пользователя в системе
                  example: "03e40c24-1d2c-4480-90e7-ad58cd17192f"
                amount:
                  type: string
                  description: Сумма платежа
                  example: "1000"
                currency:
                  type: string
                  description: Валюта платежа
                  example: "RUB"
                provider:
                  type: string
                  description: Провайдер платежа
                  example: "Stripe"
                match_id:
                  type: string
                  description: Идентификатор матча
                  example: "03e40c24-1d2c-4480-90e7-ad58cd17192f"
                ticket_id:
                  type: string
                  description: Идентификатор билета
                  example: "03e40c24-1d2c-4480-90e7-ad58cd17192f"
              required:
                - user_id
                - amount
                - currency
                - provider
                - match_id
                - ticket_id
      responses:
        '200':
          description: Платеж создан

  /payments/{id}/refund:
    post:
      summary: Возврат средств
      description: Возврат средств за платеж по его идентификатору
      operationId: refundPayment
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор платежа
          schema:
            type: string
      responses:
        '200':
          description: Средства возвращены
        '404':
          description: Платеж не найден

  /payments/webhook:
    post:
      summary: Получение уведомления о платеже
      description: Получение уведомления о платеже от провайдера
      operationId: paymentWebhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payment_id:
                  type: string
                  description: Идентификатор платежа
                  example: "03e40c24-1d2c-4480-90e7-ad58cd17192f"
                status:
                  type: string
                  description: Статус платежа
                  example: "success"
              required:
                - payment_id
                - status
      responses:
        '200':
          description: Уведомление получено

  /payments/{id}/status:
    post:
      summary: Получение статуса платежа
      description: Получение статуса платежа по его идентификатору
      operationId: getPaymentStatus
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор платежа
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                operation_type:
                  type: string
                  description: Тип операции (PAYMENT/REFUND)
                  example: "PAYMENT"
              required:
                - operation_type
      responses:
        '200':
          description: Статус платежа получен
        '404':
          description: Платеж не найден
  /payments/provider/add:
    post:
      summary: Добавление провайдера
      description: Добавление провайдера платежей
      operationId: addProvider
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                provider_name:
                  type: string
                  description: Название провайдера
                  example: "Stripe"
                provider_description:
                  type: string
                  description: Описание провайдера
                  example: "Платежный провайдер Stripe"
              required:
                - provider_name
                - provider_description
      responses:
        '200':
          description: Провайдер добавлен

  /payments/providers:
    get:
        summary: Получение списка провайдеров
        description: Получение списка всех провайдеров платежей
        operationId: getProviders
        responses:
            '200':
              description: Список провайдеров получен

  /user/{id}/payments:
    get:
        summary: Получение списка платежей пользователя
        description: Получение списка всех платежей пользователя
        operationId: getUserPayments
        parameters:
          - name: id
            in: path
            required: true
            description: Идентификатор пользователя
            schema:
              type: string
        responses:
            '200':
              description: Список платежей получен
            '404':
              description: Платежи не найдены

  /user/{id}/refunds:
    get:
      summary: Получение списка возвратов пользователя
      description: Получение списка всех возвратов пользователя
      operationId: getUserRefunds
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор пользователя
          schema:
            type: string
      responses:
          '200':
              description: Список возвратов получен
          '404':
              description: Возвраты не найдены