openapi: 3.0.0
info:
  title: AdminService API
  version: 1.0.0
  description: API сервиса администратора

servers:
  - url: http://localhost:8082
    description: Локальный сервер разработки

paths:
  /add_organizer_request:
    post:
      summary: Добавить запрос на становление организатором
      description: Принимает запрос организатора с email, компанией и ИНН.
      operationId: addOrganizerRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email организатора
                  example: "organizer@example.com"
                company:
                  type: string
                  description: Название компании организатора
                  example: "Example Company"
                tin:
                  type: string
                  description: ИНН компании организатора
                  example: "1234567890"
              required:
                - email
                - company
                - tin
      responses:
        '200':
          description: Запрос добавлен успешно
          content:
            text/plain:
              example: "sucess"
        '400':
          description: Неверный запрос
          content:
            text/plain:
              example: "bad request"