openapi: 3.0.0
info:
  title: AdminService API
  version: 1.0.0
  description: API сервиса администратора

servers:
  - url: http://localhost:8082
    description: Локальный сервер разработки

paths:
  /admin/add_organizer:
    post:
      summary: Запрос на добавление организатора
      description: Принимает запрос организатора с email, компанией и ИНН.
      operationId: addOrganizerRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email организатора
                  example: "organizer@example.com"
                company:
                  type: string
                  description: Название компании организатора
                  example: "Example Company"
                tin:
                  type: string
                  description: ИНН компании организатора
                  example: "1234567890"
              required:
                - email
                - company
                - tin
      responses:
        '200':
          description: Запрос добавлен успешно
        '400':
          description: Неверный запрос

  /admin/process_organizer:
    post:
      summary: Обработка запроса на добавление организатора
      description: Принимает запрос организатора с email, компанией и ИНН и добавляет его в базу данных.
      operationId: processOrganizerRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: email организатора
                  example: "organizer_email@gmail.com"
                company:
                  type: string
                  description: Название компании организатора
                  example: "KFC"
                tin:
                  type: string
                  description: ИНН компании организатора
                  example: "1234567890"
              required:
                - email
                - company
                - tin
    responses:
        '200':
            description: Организатор добавлен успешно

  /admin/pending_requests:
    get:
      summary: Получение списка ожидающих запросов
      description: Возвращает список ожидающих запросов на добавление организаторов.
      operationId: getPendingRequests
      responses:
        '200':
          description: Список запросов получен успешно
        '400':
          description: Неверный запрос