openapi: 3.0.0
info:
  title: TicketsService API
  version: 1.0.0
  description: API сервиса билетов

servers:
  - url: http://localhost:8005
    description: Локальный сервер разработки

paths:
  /ticket/{match_id}/add:
    post:
      summary: Добавление билета
      description: Принимает запрос на добавление билета на матч в формате CSV
      parameters:
        - name: match_id
          in: path
          required: true
          description: Уникальный идентификатор матча
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                tickets:
                  type: string
                  format: binary
                  description: CSV-файл с билетами
      operationId: addTicket
      responses:
        '201':
          description: Билет добавлен
        '400':
          description: Неверный запрос
  /ticket/{match_id}/get:
    get:
      summary: Получение билетов
      description: Получение списка билетов на матч
      parameters:
        - name: match_id
          in: path
          required: true
          description: Уникальный идентификатор матча
          schema:
            type: string
      operationId: getTickets
      responses:
        '200':
          description: Список билетов
        '400':
          description: Неверный запрос
  /ticket/{match_id}/delete:
    delete:
      summary: Удаление билета
      description: Удаление билета по его идентификатору
      parameters:
        - name: match_id
          in: path
          required: true
          description: Уникальный идентификатор матча
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                tickets:
                  type: string
                  format: binary
                  description: CSV-файл с билетами
      operationId: deleteTicket
      responses:
        '200':
          description: Билет удален
        '400':
          description: Неверный запрос
  /ticket/{id}/reserve:
    put:
      summary: Бронирование билета
      description: Бронирование билета по его идентификатору
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор матча
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                match_id:
                  type: string
                  description: Уникальный идентификатор матча
                  example: 1
                user_id:
                  type: string
                  description: ID юзера бронирующего билет
                  example: 1
      operationId: reserveTicket
      responses:
        '200':
          description: Билет забронирован
        '400':
          description: Неверный запрос

  /ticket/{id}/cancel:
    put:
      summary: Отмена бронирования билета
      description: Отмена бронирования по идентификатору билета
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор матча
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                match_id:
                  type: string
                  description: Уникальный идентификатор матча
                  example: 1
                user_id:
                  type: string
                  description: ID юзера бронирующего билет
                  example: 1
      operationId: cancelReserveTicket
      responses:
        '200':
          description: Бронь отменена
        '400':
          description: Неверный запрос