openapi: 3.0.0
info:
  title: TicketsService API
  version: 1.0.0
  description: API сервиса билетов

servers:
  - url: http://localhost:8005
    description: Локальный сервер разработки

paths:
  /tickets/{match_id}/add:
    post:
      summary: Добавление билета
      description: Принимает запрос на добавление билета на матч в формате CSV
      parameters:
        - name: match_id
          in: path
          required: true
          description: Уникальный идентификатор матча
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                tickets:
                  type: string
                  format: binary
                  description: CSV-файл с билетами
      operationId: addTicket
      responses:
        '201':
          description: Билет добавлен
        '400':
          description: Неверный запрос
  /tickets/{match_id}/get:
    get:
        summary: Получение билетов
        description: Получение списка билетов на матч
        parameters:
          - name: match_id
            in: path
            required: true
            description: Уникальный идентификатор матча
            schema:
                type: string
        operationId: getTickets
        responses:
            '200':
              description: Список билетов
            '400':
              description: Неверный запрос