openapi: 3.0.0
info:
  title: UserService API
  version: 1.0.0
  description: User service API

servers:
  - url: http://localhost:8004
    description: Local development server

paths:
  /user/create_account:
    post:
      summary: Create user account
      description: Create user account with name, last_name, email
      operationId: addUserRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User email
                  example: "nvzakrevskii@gmai.com"
                name:
                  type: string
                  description: User`s name
                  example: "Nazar"
                last_name:
                  type: string
                  description: User`s last name
                  example: "Zakrevski"
              required:
                - email
                - name
                - last_name
      responses:
        '201':
          description: User account created
        '409':
          description: Bad request

  /user/:id/update_account:
    put:
      summary: Request to update user info
      description: Update user info with name, last_name, email
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User`s name
                  example: "Mark"
                last_name:
                  type: string
                  description: User`s last name
                  example: "Dergilev"
                email:
                  type: string
                  description: User email
                  example: "madergilev@gmail.com"
                birthday:
                  type: string
                  description: User birthday
                  example: "1999-12-12"
                phone_number:
                  type: string
                  description: User phone number
                  example: "+791623456789"
              required:
                - name
                - last_name
                - email
                - birthday
                - phone_number
      responses:
        '200':
          description: User account updated
        '400':
          description: Bad request
        '404':
          description: User account not found

  /user/:id/get_account_info:
    get:
      summary: Get user account info
      description: Get user account info
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: string
      responses:
          '200':
            description: User account info
          '404':
            description: User account not found

