main_url = "http://localhost:8000"
user_url = "http://localhost:8001"
auth_url = "http://localhost:8002"
admin_url = "http://localhost:8003"
organizer_url = "http://localhost:8004"
matches_url = "http://localhost:8005"
tickets_url = "http://localhost:8006"
email_url = "http://localhost:8010"
frontend_url = "http://localhost:3000"
kafka_url = "localhost:9092"