main_url = "http://orchestrator:8000"
user_url = "http://user:8001"
auth_url = "http://auth:8002"
admin_url = "http://admin:8003"
organizer_url = "http://organizer:8004"
matches_url = "http://matches:8005"
tickets_url = "http://tickets:8006"
frontend_url = "http://localhost:3000"