name: DevBranchTesting CI

on:
  push:
    branches:
<<<<<<< HEAD
<<<<<<< HEAD
      - Nazar_Zakrevski
=======
      - dev
>>>>>>> 160d16c (test update password added, some fix in auth)
=======
      - Nazar_Zakrevski
>>>>>>> 8fad90d (try)
  pull_request:
    branches:
      - dev

<<<<<<< HEAD
<<<<<<< HEAD

=======
>>>>>>> 160d16c (test update password added, some fix in auth)
=======

>>>>>>> 805ed89 (try)
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AuthorizationService, OrganizerService]

    steps:
      - uses: actions/checkout@v2

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 688ea39 (using docker-compose instead of dummy build)
      - name: Установка Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Запуск сервисов
        run: |
<<<<<<< HEAD
<<<<<<< HEAD
          docker-compose up -d 

=======
>>>>>>> 160d16c (test update password added, some fix in auth)
=======
          cd ${{ matrix.service }}
=======
>>>>>>> 7a9638f (fix)
          docker-compose up -d 

>>>>>>> 688ea39 (using docker-compose instead of dummy build)
      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          cd ${{ matrix.service }}
          python3 -m pip install --upgrade pip
<<<<<<< HEAD
<<<<<<< HEAD
          python3 -m pip install -r requirements.txt
=======
>>>>>>> 160d16c (test update password added, some fix in auth)
=======
          python3 -m pip install -r requirements.txt
>>>>>>> 980bb8d (try)

      - name: Запуск тестов
        run: |
          cd ${{ matrix.service }}
          pytest --maxfail=1 --disable-warnings -q
