name: DevBranchTesting CI

on:
  push:
    branches:
<<<<<<< HEAD
      - Nazar_Zakrevski
=======
      - dev
>>>>>>> 160d16c (test update password added, some fix in auth)
  pull_request:
    branches:
      - dev

<<<<<<< HEAD

=======
>>>>>>> 160d16c (test update password added, some fix in auth)
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AuthorizationService, OrganizerService]

    steps:
      - uses: actions/checkout@v2

<<<<<<< HEAD
      - name: Установка Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Запуск сервисов
        run: |
          docker-compose up -d 

=======
>>>>>>> 160d16c (test update password added, some fix in auth)
      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          cd ${{ matrix.service }}
          python3 -m pip install --upgrade pip
<<<<<<< HEAD
          python3 -m pip install -r requirements.txt
=======
>>>>>>> 160d16c (test update password added, some fix in auth)

      - name: Запуск тестов
        run: |
          cd ${{ matrix.service }}
          pytest --maxfail=1 --disable-warnings -q
