name: DevBranchTesting CI

on:
  push:
    branches:
      - Nazar_Zakrevski
  pull_request:
    branches:
      - dev


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AuthorizationService, OrganizerService]

    steps:
      - uses: actions/checkout@v2

      - name: Установка Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Запуск сервисов
        run: |
          cd ${{ matrix.service }}
          docker-compose up -d 

      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          cd ${{ matrix.service }}
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Запуск тестов
        run: |
          cd ${{ matrix.service }}
          pytest --maxfail=1 --disable-warnings -q
